version: '3.2'

services:
        app:
                container_name: logging_service_app
                build: docker/logging_service_app
                restart: always
                volumes:
                        - .:${GO_PROJECT_DIR}
                environment:
                        DEBUG: ${DEBUG}
                        GIN_MODE: ${GIN_MODE}
                        GO_WORK_DIR: ${GO_PROJECT_DIR}/app
                        CLICKHOUSE_SERVER: tcp://logging_service_clickhouse:9000
                working_dir: ${GO_PROJECT_DIR}/app
                ports:
                        - 8080:8080
                        - 2345:2345
                depends_on:
                  - clickhouse
                links:
                  - clickhouse
                security_opt:
                        - seccomp:unconfined

        clickhouse:
                container_name: logging_service_clickhouse
                build: docker/clickhouse
                restart: always
                ports:
                        - 9000:9000
                volumes:
                        - ./data:/var/lib/clickhouse
